# Generated by Django 4.0.3 on 2022-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.CharField(max_length=36, verbose_name='Oracle ID')),
                ('back_name', models.CharField(blank=True, max_length=100, verbose_name='Back')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mana_cost', models.CharField(blank=True, max_length=50, verbose_name='Mana Cost')),
                ('cmc', models.CharField(max_length=2, verbose_name='MV')),
                ('colors', models.CharField(blank=True, max_length=15, verbose_name='Colors')),
                ('color_identity', models.CharField(blank=True, max_length=15, verbose_name='Identity')),
                ('art_crop', models.CharField(blank=True, max_length=200, verbose_name='Art')),
                ('type_line', models.CharField(max_length=100, verbose_name='Type')),
                ('set', models.CharField(max_length=5, verbose_name='Set')),
                ('set_name', models.CharField(max_length=50, verbose_name='Set')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
                ('legalities', models.CharField(max_length=250, verbose_name='Legalities')),
                ('oracle_text', models.CharField(blank=True, max_length=1000, verbose_name='Oracle')),
                ('flavor_text', models.CharField(blank=True, max_length=1000, verbose_name='Flavor')),
                ('artist', models.CharField(blank=True, max_length=50, verbose_name='Artist')),
                ('power', models.CharField(blank=True, max_length=3, verbose_name='Power')),
                ('toughness', models.CharField(blank=True, max_length=3, verbose_name='Toughness')),
                ('rarity', models.CharField(max_length=1, verbose_name='Rarity')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Deck Name')),
                ('format', models.CharField(max_length=50, verbose_name='Format')),
                ('main_cards', models.CharField(max_length=10000, verbose_name='Main Deck')),
                ('side_cards', models.CharField(max_length=10000, verbose_name='Sideboard')),
                ('commander', models.CharField(max_length=50, verbose_name='Commander')),
            ],
        ),
    ]
